### ISSUE TITLE
Duplicating with vacuum hoppers

### ISSUE THREAD

**Issue by airoons** [Rusketh/ComparableHoppers2#1]
1) Q: What is your name on spigot?
   A: TheIronMinerLv

2) Q: What is your Spigot build?
   A: PaperSpigot 1.8.8

3) Q: What is your CH2 version?
   A: CH2-2.3.1 for 1.8.8 & 1.12.x

4) Q: Do you get any errors in console?
   A: No errors

5) Q: Have you read the full OP for the resource (https://www.spigotmc.org/resources/comparable-hoppers-2.45058/
   A: Yes
   
6) Q: Please describe the issue you are having.
   A: It is somehow possible to dupe items with vacuum upgrade, it is hard to reproduce, but my players are duplicating items

7) Q: Please describe how to replicate the issue, being as specific as possible.
   A: With two overlapping vacuum hoppers, as I suppose.
    
8) Q: Anything else you think we should know about your issue?
    A: Please fix as soon as possible!

**Comment by Rusketh** [comment]
Unfortunately with out knowing how to fully replicate the issue, it will not be possible to investigate.

**Comment by airoons** [comment]
2 or more hoppers with vacuum upgrade,but their "vacuum range" need to overlap. Just throw item and item will get duplicated (multiple hoppers will pick up)

**Comment by Rusketh** [comment]
Thank you, a patch is currently being tested and will be released soon.

**Comment by Rusketh** [comment]
The patch has been tested and is now available for download.

Thank you.
