### ISSUE TITLE
Ender hopper suddenly stopped working

### ISSUE THREAD

**Issue by Nesseley** [Rusketh/ComparableHoppers2#11]
Q: What is your name on spigot?
A: Nesseley

Q: What is your Spigot build?
A: 1.12.2

Q: What is your CH2 version?
A: CH2 2.3.6 for MC 1.12.x

Q: Do you get any errors in console?
A: No

Q: Have you read the full OP for the resource (https://www.spigotmc.org/resources/comparable-hoppers-2.45058/
If not you should probably do so and double check you have set everything up correctly.
A: Yes
   
6) Q: Please describe the issue you are having.
   A: When trying to shift + rightclick a Ender upgrade to a chest nothing happens. (The enderpearl only goes on the "cooldown" timer in the invenotry) No messages, nothing.

7) Q: Please describe how to replicate the issue, being as specific as possible.
   A: I am not really sure, as the upgrade used to work. Does'nt work on a fresh install too.

8) Other
  A: Had to delete my world to get ender-filter to work again. Then i reloaded the server and ender-filter no longer works (doesnt register invenotry)

**Comment by Rusketh** [comment]
Should be fixed in the next ver, for now when they stop working use.

/hopper-reload
