### ISSUE TITLE
Ender upgrade not working [MC 1.12.X]

### ISSUE THREAD

**Issue by downboy** [Rusketh/ComparableHoppers2#12]
1) Q: What is your name on spigot?
   A: nukels

2) Q: What is your Spigot build?
   E.G 1.8.8, 1.12.1, 1.12.2
   A: 1.12.x

3) Q: What is your CH2 version?
   A: CH 2.3.7 for MC 1.12.x

4) Q: Do you get any errors in the console?
   A: No

5) Q: Have you read the full OP for the resource (https://www.spigotmc.org/resources/comparable-hoppers-2.45058/
   If not you should probably do so and double check you have set everything up correctly.
   A: Yes
   
6) Q: Please describe the issue you are having.
   E.G When trying to craft a comparable upgrade a console error happens (as mentioned in Q4).
   A: the moment you click(shift + right click) a container with an ender upgrade, the message don't show. Also, the ender upgrade can be used as a normal ender pearl. for me, this means that the plugin doesn't register something. 

7) Q: Please describe how to replicate the issue, being as specific as possible.
   E.G Craft a comparable upgrade using the default recipe.
   A: Get an ender upgrade > click a container > no msg shows
        Get an ender upgrade > shift + right click air > you will be teleported to a location.
   
8) Q: Anything else you think we should know about your issue?
    A: I didn't test this with 1.8 only on 1.12, I also ask for support on discord and they can confirm this issue!

**Comment by Rusketh** [comment]
Can i see your config file please. Some times this can happen if you include formatting codes for text colour in the yml file with out using quotations around the full string.

Please upload your yml file to gist.github.com and link me the the gist.

Thank you

**Comment by Nesseley** [comment]
I got the same problem, this is my config:
https://pastebin.com/WmanzFN4

Note that this config worked before the latest update!

**Comment by Rusketh** [comment]
config seems fine, will look into it further.

**Comment by Rusketh** [comment]
Thank you and Fixed as of 2.3.8.
