### ISSUE TITLE
Vacuum hoppers deleting items it's picking up.

### ISSUE THREAD

**Issue by Nesseley** [Rusketh/ComparableHoppers2#16]
**1) Q: What is your name on spigot?**
   A: Nesseley

**2) Q: What is your Spigot build?**
   A: 1.12.2

**3) Q: What is your CH2 version?**
   A: CH2.4.3 - MC1.12.x

**4) Q: Do you get any errors in console?**
   A: No.

**5) Q: Have you read the full OP for the resource (https://www.spigotmc.org/resources/comparable-hoppers-2.45058/**
   A: Yes
   
**6) Q: Please describe the issue you are having.**
   A: Vacuum hoppers are deleting items. 

**7) Q: Please describe how to replicate the issue, being as specific as possible.**
   A: Simply trow a stack of whatever into a vacuum hopper. It will only pick up 1 and delete the rest of the items.
   
**8) Q: Anything else you think we should know about your issue?**
    A: No

**Comment by Rusketh** [comment]
Thank you, this has been fixed for the 2.5 release.
