### ISSUE TITLE
Warning message at server boot

### ISSUE THREAD

**Issue by Baktus79** [Rusketh/ComparableHoppers2#17]
This form is for submitting issues with Comparable hoppers 2 for Spigot, please make sure to fill at all questions properlly as failing to do so will prevent us from helping replicate/fixing your issue.
This issue tracker is for Comparbale Hopper 2 Buyers only, if you have an issue with the plugin on a server but you are not the server owner please have the server owner or the plugins buyer fill out this form.

1) Q: What is your name on spigot?
   Failure to provide this will result in your issue being instantly closed,
   if you are not a legit plugin buyer then your issue will also be dismissed.
   A: Baktus79

2) Q: What is your Spigot build?
   E.G 1.8.8, 1.12.1, 1.12.2
   A: 1.12.2 (Not using Spigot, but rather Paper)

3) Q: What is your CH2 version?
   E.G CH 2.3.1 for MC 1.12.x
   A: CH 2.4.3 for MC 1.12.x

4) Q: Do you get any errors in console?
   If the answer is yes, please go into the root of your server and find the logs directory and find 'latest.log' and open it.
   Then head over to http://gist.github.com create a new gist posting the error from the log file into the gist, we ask you use gist as it makes it easier for us to search.
   It is really imporant that this come from the log file and not the console itself, as the console will hide important information about the error.
   A: https://gist.github.com/Baktus79/80b2e0d037710b8bd79d579b733f062b

5) Q: Have you read the full OP for the resource (https://www.spigotmc.org/resources/comparable-hoppers-2.45058/
   If not you should probably do so and double check you have set everything up correctly.
   A: Yes
   
6) Q: Please describe the issue you are having.
   E.G When trying to craft a comparable upgrade a conole error happens (as mentioned in Q4).
   A: Im getting this warning message.

7) Q: Please describe how to replicate the issue, being as specific as possible.
   E.G Craft a comparable upgrade using the default recipie.
   A: Start up the plugin
   
8) Q: Anything else you think we should know about your issue?
    A: No

**Comment by Rusketh** [comment]
I believe this is an issue related to paper spigot itself,it is complaining about me using a deprecated method how ever regular spigot doesn't care. Once I am back up with an internet connection I can look into this.

**Comment by Rusketh** [comment]
Simple fix, a 2.5.1 patch should be released later today to fix this for paper spigot 1.12.2
