### ISSUE TITLE
Updating Scheme - [SQLITE_ERROR] 

### ISSUE THREAD

**Issue by Blueeyestar** [Rusketh/ComparableHoppers2#19]
I always get this error message !!

**> [K[10:54:46 INFO]: [global] Updating Scheme - [SQLITE_ERROR] SQL error or missing database (duplicate column name: placer), ignore this. > [K[10:54:46 INFO]: [global] Updating Scheme - [SQLITE_ERROR] SQL error or missing database (duplicate column name: roundrobin), ignore this. > [K[10:54:46 INFO]: [global] Updating Scheme - [SQLITE_ERROR] SQL error or missing database (duplicate column name: ender), ignore this. > [K[10:54:46 INFO]: [global] Updating Scheme - [SQLITE_ERROR] SQL error or missing database (duplicate column name: port), ignore this.** 

that would belong to the hopper plugin, right?

**Comment by Rusketh** [comment]
This is correct, your also notice these lines are affixed with "ignore this".

This is just because when CH2 loads a world it checks to make sure the mysql db is compatible, doing so creates those error messages.

**Comment by Blueeyestar** [comment]
Good to know then I will pay no attention to this. Would it be possible to make a funnel that is considered an automatic crafter? That would be the tip of the plugin :)
