### ISSUE TITLE
Speed Upgrade | Stacked items bug

### ISSUE THREAD

**Issue by Melowelsa** [Rusketh/ComparableHoppers2#2]
1) Q: What is your name on spigot?
   A: __Melowelei__ 

2) Q: What is your Spigot build?
   A: Spigot-v1_12 (git-Spigot-596221b-86aa17f | 1.12-R0.1-SNAPSHOP).

3) Q: What is your CH2 version?
   A: CH2 2.3.3 for MC 1.12.x

4) Q: Do you get any errors in console?
   A: There is no error.

5) Q: Have you read the full OP for the resource (https://www.spigotmc.org/resources/comparable-hoppers-2.45058/
   A: Yes, I read the full OP.
   
6) Q: Please describe the issue you are having.
   A: When you stack EnderPearls by 64 and drop it into Comparable Hopper, you didn't get back of the total amount you droped in.

7) Q: Please describe how to replicate the issue, being as specific as possible.
   A: To replicate the issue, take stacks of 64 EnderPearls, maybe 3 for example.
Then, add a chest, and hopper pointing into this chest, get the **Hopper Upgrade Speed** and add him to the hopper to upgrade it.
After this, drop the 3 stacks of EnderPearls into the hopper, and look the chest, there is no more the 3 stacks but 1 stack & 32. 
   
10) Q: Anything else you think we should know about your issue?
    A: It's the same issue for all item not stackable normaly (like bucket).

**Comment by Rusketh** [comment]
Ender-pearls can only stack upto 16. I have tested with 3 stacks of 16 ender pearls on 2.3.3 and was unable to replicate the issue. I have also tried other stacks including buckets and have still been unable to replicate the issue.

**Comment by Rusketh** [comment]
Ok, so I have done more testing.
Appears items listing is broken, when comparing more than one item.

**Comment by Rusketh** [comment]
Thank you,

We have found this bug exists in both 1.8.8 and 1.12.x but are unfortunately only able to fix for 1.12.x as of the moment.

This will be fixed in CH-2.3.3 for 1.12.x, white lists will also be moved to a separate inventory from that of the hopper.

**Comment by Rusketh** [comment]
Should be fixed as of 2.3.4.
