### ISSUE TITLE
CH2 does not work with non default world paths

### ISSUE THREAD

**Issue by enaut** [Rusketh/ComparableHoppers2#21]
This form is for submitting issues with Comparable hoppers 2 for Spigot, please make sure to fill at all questions properlly as failing to do so will prevent us from helping replicate/fixing your issue.
This issue tracker is for Comparbale Hopper 2 Buyers only, if you have an issue with the plugin on a server but you are not the server owner please have the server owner or the plugins buyer fill out this form.

1) Q: What is your name on spigot?
   Failure to provide this will result in your issue being instantly closed,
   if you are not a legit plugin buyer then your issue will also be dismissed.
   A: enaut

2) Q: What is your Spigot build?
   E.G 1.8.8, 1.12.1, 1.12.2
   A: final build for 1.12.2

3) Q: What is your CH2 version?
   E.G CH 2.3.1 for MC 1.12.x
   A:  CH 2.4.1

4) Q: Do you get any errors in console?
   A: https://gist.github.com/enaut/b01b9a12e359a8214ac94cc0b77699cf

5) Q: Have you read the full OP for the resource (https://www.spigotmc.org/resources/comparable-hoppers-2.45058/
   If not you should probably do so and double check you have set everything up correctly.
   A: Yes / No
   
6) Q: Please describe the issue you are having.
   E.G When trying to craft a comparable upgrade a conole error happens (as mentioned in Q4).
   A: Answer Here

Comparable hoppers seems to not respect the custom directory for worlds that can be set in spigot (I think bukkit too). The setting is described here: https://www.spigotmc.org/wiki/start-up-parameters/

> --world-dir <directory>
> Aliases: -W <directory> or --universe <directory> or --world-container <directory>
> Default: ./
> This parameter will put all worlds your server uses into a specific directory, it's useful if you have many folders inside in the main server directory.
> Please pay attention to the uppercase for the first alias. 

7) Q: Please describe how to replicate the issue, being as specific as possible.
   E.G Craft a comparable upgrade using the default recipie.
   A: Change the world-container in the `spigot.yml` or via commandline.
   
8) Q: Anything else you think we should know about your issue?
    A: Answer Here

**Comment by Rusketh** [comment]
This has been amended in the CH2.5.5 releases.
