### ISSUE TITLE
Ender Hopper Duplication Bug

### ISSUE THREAD

**Issue by astirling** [Rusketh/ComparableHoppers2#24]
This form is for submitting issues with Comparable hoppers 2 for Spigot, please make sure to fill at all questions properlly as failing to do so will prevent us from helping replicate/fixing your issue.
This issue tracker is for Comparbale Hopper 2 Buyers only, if you have an issue with the plugin on a server but you are not the server owner please have the server owner or the plugins buyer fill out this form.

1) Q: What is your name on spigot?
   Failure to provide this will result in your issue being instantly closed,
   if you are not a legit plugin buyer then your issue will also be dismissed.
   A: Magarathin

2) Q: What is your Spigot build?
   E.G 1.8.8, 1.12.1, 1.12.2
   A: Paper version git-Paper-317 (MC: 1.13.1)

3.1) Q: What is your product?
   E.G: CH2 Basic, CH2 Paid, CH2 Spawners...
   A: CH2 Paid
   
3.2) Q: What is your Product version?
   E.G CH 2.3.1 for MC 1.12.x
   A: Comparable Hoppers version 2.5.6 for MC1.13.1

4) Q: Do you get any errors in console? No
   If the answer is yes, please go into the root of your server and find the logs directory and find 'latest.log' and open it.
   Then head over to http://gist.github.com create a new gist posting the error from the log file into the gist, we ask you use gist as it makes it easier for us to search.
   It is really imporant that this come from the log file and not the console itself, as the console will hide important information about the error.
   A: Paste your gist link here

5) Q: Have you read the full OP for the resource (https://www.spigotmc.org/resources/comparable-hoppers-2.45058/
   If not you should probably do so and double check you have set everything up correctly.
   A: Yes
   
6) Q: Please describe the issue you are having.
   E.G When trying to craft a comparable upgrade a conole error happens (as mentioned in Q4).
   A: When you set the target of the Ender Hopper to itself it will duplicate the item it is transferring to itself.

7) Q: Please describe how to replicate the issue, being as specific as possible.
   E.G Craft a comparable upgrade using the default recipie.
   A: Shift right click the hopper with the Ender upgrade then shift right click the same hopper with the Ender upgrade.
   
8) Q: Anything else you think we should know about your issue?
    A: Not at this time

**Comment by Rusketh** [comment]
How are you achieving this?
If you try to install an ender upgrade linked to the block your installing it into it is rejected.
Also in all transfer functions, if the source and destination inventories are the same it will not perform the transfer.
From a code perspective this is impossible.

**Comment by astirling** [comment]
video of me replicating the issue
https://youtu.be/ICc9D4LVvTs

**Comment by Rusketh** [comment]
Ok, time to test.

**Comment by Rusketh** [comment]
Confirmed.

**Comment by Rusketh** [comment]
Fixed as of 2.5.7 for MC 1.13.1
