### ISSUE TITLE
Comparable Hoppers with advanced filter upgrade do not filter "non-advanced" materials

### ISSUE THREAD

**Issue by enaut** [Rusketh/ComparableHoppers2#29]
1) Q: What is your name on spigot?
   A: enaut

2) Q: What is your Spigot build?
1.14

3.1) Q: What is your product?
   A: ComparableHoppers2
   
3.2) Q: What is your Product version?
   A:  v2.6.4

4) Q: Do you get any errors in console?
   A: There have been Nullpointer error before but now there are no errors anymore

5) Q: Have you read the full OP for the resource
   A: Yes
   
6) Q: Please describe the issue you are having.
   A: advanced filter hoppers still can't filter cobbleston

7) Q: Please describe how to replicate the issue, being as specific as possible.
   A: The test setup: A chest above the chest an advanced filter pusching in the chest. Above the filterhopper another chest/hopper containing white wool and cobblestone. The midle filterhopper  has cobblestone and white wool in it's  whitelist.
7.2) Q: Result.
   A: the wool goes down into the bottom chest as it should, however the cobblestone stays in the upper chest despite it is on the whitelist.
   
8) Q: Anything else you think we should know about your issue?
    A: has been discussed on discord

**Comment by Rusketh** [comment]
We will look into this for the next version.

**Comment by Rusketh** [comment]
I have tested this bug in 1.14 and was unable to replicate this behavior. I shall be running more tests tonight, but 1.14 could itself be the cause since it seems to have a lot of issues at the moment with comparing nbt flags.

**Comment by enaut** [comment]
Now I created a video... see discord.

**Comment by enaut** [comment]
Thanks for the fix.
