### ISSUE TITLE
Ender Upgrade issue (upgrade removing)

### ISSUE THREAD

**Issue by airoons** [Rusketh/ComparableHoppers2#3]
Soo I'll be short - no errors in console, PaperSpigot 1.8.8, newest CH2. 

I stack 4 ender upgrades in my inventory. So I try to use one, when I successfully apply an upgrade to a hopper, all 4 upgrades are removed from my inventory. 

Please fix!

**Comment by Rusketh** [comment]
Please recreate this issue using the appropriate template. Thank you
