### ISSUE TITLE
Ender upgrade issue

### ISSUE THREAD

**Issue by airoons** [Rusketh/ComparableHoppers2#4]
This form is for submitting issues with Comparable hoppers 2 for Spigot, please make sure to fill at all questions properlly as failing to do so will prevent us from helping replicate/fixing your issue.
This issue tracker is for Comparbale Hopper 2 Buyers only, if you have an issue with the plugin on a server but you are not the server owner please have the server owner or the plugins buyer fill out this form.

1) Q: What is your name on spigot?
   Failure to provide this will result in your issue being instantly closed,
   if you are not a legit plugin buyer then your issue will also be dismissed.
   A: TheIronMinerLv

2) Q: What is your Spigot build?
   E.G 1.8.8, 1.12.1, 1.12.2
   A: PaperSpigot 1.8.8

3) Q: What is your CH2 version?
   E.G CH 2.3.1 for MC 1.12.x
   A: CH-2.3.3 for MC 1.8.x

4) Q: Do you get any errors in console?
   If the answer is yes, please go into the root of your server and find the logs directory and find 'latest.log' and open it.
   Then head over to http://gist.github.com create a new gist posting the error from the log file into the gist, we ask you use gist as it makes it easier for us to search.
   It is really imporant that this come from the log file and not the console itself, as the console will hide important information about the error.
   A: No errors

5) Q: Have you read the full OP for the resource (https://www.spigotmc.org/resources/comparable-hoppers-2.45058/
   If not you should probably do so and double check you have set everything up correctly.
   A: Yes
   
6) Q: Please describe the issue you are having.
   E.G When trying to craft a comparable upgrade a conole error happens (as mentioned in Q4).
   A: I stack 4 ender upgrades in my inventory. So I try to use one, when I successfully apply an upgrade to a hopper, all 4 upgrades are removed from my inventory.

7) Q: Please describe how to replicate the issue, being as specific as possible.
   E.G Craft a comparable upgrade using the default recipie.
   A: Read previous A
   
9) Q: Please describe how to replicate the issue, being as specific as possible.
   E.G Craft a comparable upgrade using the default recipie.
   A: Read previous A
   
10) Q: Anything else you think we should know about your issue?
    A: Just try yourself and fix

**Comment by Rusketh** [comment]
This issue has been fixed and will be included released in CH-2.3.3
