### ISSUE TITLE
Error spam in console, which possible lead to crash

### ISSUE THREAD

**Issue by airoons** [Rusketh/ComparableHoppers2#5]
This form is for submitting issues with Comparable hoppers 2 for Spigot, please make sure to fill at all questions properly as failing to do so will prevent us from helping replicate/fixing your issue.
This issue tracker is for Comparable Hopper 2 Buyers only, if you have an issue with the plugin on a server but you are not the server owner please have the server owner or the plugins buyer fill out this form.

1) Q: What is your name on spigot?
   Failure to provide this will result in your issue being instantly closed,
   if you are not a legit plugin buyer then your issue will also be dismissed.
   A: TheIronMinerLv

2) Q: What is your Spigot build?
   E.G 1.8.8, 1.12.1, 1.12.2
   A: PaperSpigot 1.8.8

3) Q: What is your CH2 version?
   E.G CH 2.3.1 for MC 1.12.x
   A: CH2 2.3.3 for 1.8.8

4) Q: Do you get any errors in the console?
   If the answer is yes, please go to the root of your server and find the logs directory and find 'latest.log' and open it.
   Then head over to http://gist.github.com create a new gist posting the error from the log file into the gist, we ask you use gist as it makes it easier for us to search.
   It is really important that this comes from the log file and not the console itself, as the console will hide important information about the error.
   A: https://pastebin.com/Q51ANq6N

5) Q: Have you read the full OP for the resource (https://www.spigotmc.org/resources/comparable-hoppers-2.45058/
   If not you should probably do so and double check you have set everything up correctly.
   A: Yes
   
6) Q: Please describe the issue you are having.
   E.G When trying to craft a comparable upgrade a console error happens (as mentioned in Q4).
   A: So this error spammed my console and then server suddenly crashed. I don't know what causes that.

7) Q: Please describe how to replicate the issue, being as specific as possible.
   E.G Craft a comparable upgrade using the default recipe.
   A: Read previous A
   
9) Q: Please describe how to replicate the issue, being as specific as possible.
   E.G Craft a comparable upgrade using the default recipe.
   A: Read previous A
   
10) Q: Anything else you think we should know about your issue?
    A: Just fix it, try to investigate?

**Comment by airoons** [comment]
Oh, about that crash - there was no crash-reports/crash-errors, server just froze (including console).

**Comment by Rusketh** [comment]
Could you please tell me if you are using a modified recipe, was it changed in config?

Otherwise, I have tried this in 1.8.8 on the new 2.3.4 ver of CH2 and am able to confirm I was unable to replicate this bug on the newer version.

Could you please update your plugin and attempt the crafting operation again, once done let me know your results here.

thank you

**Comment by airoons** [comment]
I don't use crafting recipes

**Comment by Rusketh** [comment]
Can you retest with the latest build and post results. Thank you.

**Comment by Rusketh** [comment]
Still waiting on feedback as to weather updated copies of this plugin are effected by this.
I have tested in 1.8.8 and 1.12.2 but was unable to replicate.

**Comment by airoons** [comment]
It is fixed, it seems like.

**Comment by Rusketh** [comment]
Ok thank you for testing. Ticket closed
