### ISSUE TITLE
Blacklist Upgrade | Crash Server

### ISSUE THREAD

**Issue by Melowelsa** [Rusketh/ComparableHoppers2#7]
1) Q: What is your name on spigot?
   A: __Melowelei__

2) Q: What is your Spigot build?
   A: Spigot-v1_12 (git-Spigot-596221b-86aa17f | 1.12-R0.1-SNAPSHOP).

3) Q: What is your CH2 version?
   A: CH2 2.3.4 for MC 1.12.x.

4) Q: Do you get any errors in console?
   A: Yes, there is : __https://hastebin.com/erezizaqod.md__

5) Q: Have you read the full OP for the resource (__https://www.spigotmc.org/resources/comparable-hoppers-2.45058/__
   A: Yes, I read the full OP.
   
6) Q: Please describe the issue you are having.
   A: When we use/interract, it make crash my server.

7) Q: Please describe how to replicate the issue, being as specific as possible.
   A: Install the "Blacklist Hopper Upgrade" into a normal hopper, then I don't know exactly, but in 3-5mins it make crash my serveur.
8) Q: Anything else you think we should know about your issue?
   A: When the plugin is not installed on my server, my server will not crash.
When the plugin are installed, my server can crash 50 times in 24H, maybe just check your code and you will find something with the error I gave you.
I have seen this error after updating to the CH2 2.3.4 for MC 1.12.x version, was not happening with the CH2 2.3.3 for MC 1.12.x.

**Comment by Rusketh** [comment]
That error is pretty serious, might be because its compiled on 1.12.2 and your on 1.12.1, I will need to run some tests to figure this out.

**Comment by Melowelsa** [comment]
I am on **Spigot-v1_12 (git-Spigot-596221b-86aa17f | 1.12-R0.1-SNAPSHOP)** and not on **1.12.1**, as I told you on the questions :3
Thanks ! ^-^'

**Comment by Melowelsa** [comment]
I have found how my server is crashing, I explain you how to doing it :
1. Take a normal hopper and place it,
2. Install on this hopper the "Comparable Hopper Upgrade" and "White list Hopper Upgrade",
3. Take some items, what you want there is no importance,
4. Sneak+click to open the "White List" inventory,
5. Place the item into the "White List" inventory using shift+clicks on the item from your inventory.

And doing so this will may crash the server.. :$
Hope this will help you to patch this bug, good luck & thank to you ! ^-^'

**Comment by Rusketh** [comment]
Ok, right so this is shift click again.
This is a bug with in spigot itself and is unrelated to my plugin and has been a bug with spigot since 1.5 i believe.
If you look on the resource op your see that its mentioned that shift clicking causes a crash error, how ever that was meant to be disabled as a work around for the spigot issue.
I will take a look tonight into seeing why the work around is not working.

**Comment by Melowelsa** [comment]
Maybe change the "Blacklist Hopper Upgrade" & "White List Hopper Upgrade" inventory of what told you in private ? I think it will be more interesting at all, but it's your choice.
Thanks for your time ! ^-^

**Comment by Melowelsa** [comment]
This issue has been fixed by Rusketh for the next public update, so I close the issue. ^*^'
Thanks for his time ! :3
