### ISSUE TITLE
Think Event | Stopped

### ISSUE THREAD

**Issue by Melowelsa** [Rusketh/ComparableHoppers2#9]
1) Q: What is your name on spigot?
   A: __Melowelei__

2) Q: What is your Spigot build?
   A: Spigot-v1_12 (git-Spigot-596221b-86aa17f | 1.12-R0.1-SNAPSHOP)

3) Q: What is your CH2 version?
   A: CH2 2.3.5 for MC 1.12

5) Q: Have you read the full OP for the resource (https://www.spigotmc.org/resources/comparable-hoppers-2.45058/
   A: Yes, I have read the full OP.
   
6) Q: Please describe the issue you are having.
   A: Sometimes, the plugin stop completly working, the hopper don't work anymore after a reload.

7) Q: Please describe how to replicate the issue, being as specific as possible.
   A: I don't know how this is happening, but maybe the "Think" event from the plugin are stopped and don't work anymore, the hoppers don't take anymore items, etc..
   
8) Q: Anything else you think we should know about your issue?
    A: We need to reload/restart the server to make it working correctly, it would be good if you can add a reload command, or make this event auto reloading when it get broken.

**Comment by Rusketh** [comment]
Added in CH2.3.6
